### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by MgOmbodorj** [PaloAltoNetworks/minemeld#1]
HI , 

After activated this extension , Minemeld engine cannot start. #

**Comment by karloluiten** [comment]
What extension are you talking about?

**Comment by MgOmbodorj** [comment]
sorry .
minemeld-cef extension

**Comment by jtschichold** [comment]
Please, could you open the bug int the minemeld-cef repo https://github.com/PaloAltoNetworks/minemeld-cef ?
Could you also include the error logs from /opt/minemeld/log/minemeld-engine.log ?
