### ISSUE TITLE
Wrong link location

### ISSUE THREAD

**Issue by jonnynux** [PaloAltoNetworks/minemeld#12]
Hi,
the **MineMeld section of the Palo Alto Networks live community** link wrote in the README.md is wrong (actual link is https://live.paloaltonetworks.com/MineMeld), it gives the following message: **The page you are trying to access was not found. Please check your URL for typos and try again.** 
Maybe the correct page is this? **https://live.paloaltonetworks.com/t5/MineMeld/ct-p/MineMeld**

Best regards,
Giorgio

**Comment by jtschichold** [comment]
Thanks ! fixed !

luigi
