### ISSUE TITLE
Typo in path for supervisorctl command

### ISSUE THREAD

**Issue by bilalbox** [PaloAltoNetworks/minemeld#14]
Luigi,

Please update the Wiki under [Building the Core VM](https://github.com/PaloAltoNetworks/minemeld/wiki/Developer's-Guide#building-the-core-vm) **step 10** which currently reads:
```
sudo -u minemeld /opt/minemeld/engine/current/bin/supervisorctl -c /opt/minemeld/local/supervisor/config/supervisord.conf status
```
To read instead:
```
sudo -u minemeld /opt/minemeld/engine/current/bin/supervisorctl -c /opt/minemeld/local/supervisor/config/supervisord.conf status
```

The supervisor directory is actually right under **/opt/minemeld**, not **/opt/minemeld/local/**. This will help users that aren't familiar with the path troubleshoot the error they will receive if they run that command as is:

> Error: could not find config file /opt/minemeld/local/supervisor/config/supervisord.conf
> For help, use /opt/minemeld/engine/current/bin/supervisorctl -h
> 

Thanks!
Nasir

**Comment by jtschichold** [comment]
Fixed ! Thanks ! It was still referring to the old path.
