### ISSUE TITLE
O365 Miner Not Retrieving IOCs

### ISSUE THREAD

**Issue by ghost** [PaloAltoNetworks/minemeld#28]
Just noticed this happened recently, but the office365.any miner isn't retrieving any IOCs. This was working without issue for almost a year. The office365.o365 miner doesn't retrieve anything either. Did MS change something on their end that the miner hasn't been updated for?

**Comment by jtschichold** [comment]
Hi @neonetos,
Microsoft has dropped the old XML feed for the a new API. You should switch to the new Miners, o365-api.* available since 0.9.50
