### ISSUE TITLE
feodotracker.domainblocklist broken

### ISSUE THREAD

**Issue by ericmartin** [PaloAltoNetworks/minemeld#29]
feodotracker.domainblocklist is pulling an HTML page, and not properly parsing the data.  An example of the output is attached.

[OUTPUT_DOMAIN_onboard_feodo.txt](https://github.com/PaloAltoNetworks/minemeld/files/2752813/OUTPUT_DOMAIN_onboard_feodo.txt)

**Comment by jtschichold** [comment]
Hi @ericmartin,
thanks for reporting this, this was fixed in minemeld-node-prototypes#96 https://github.com/PaloAltoNetworks/minemeld-node-prototypes/pull/96

If you have installed MineMeld with Ansible you can update now to get the fix
