### ISSUE TITLE
Performance problem when stdlib.listIPv4Generic node contains a large number of addresses

### ISSUE THREAD

**Issue by pgerencser** [PaloAltoNetworks/minemeld#31]
We would like to use a stdlib.listIPv4Generic miner with more than 25000 addresses. These addresses has been imported from a texfile using _minemeld-sync.py_.
My problem is that it takes around 20 seconds to list the indicators (500 pages, 50 indicators per page). During the process minemeld generates the paginator component, one CPU core is used at 100%, but other cores are not used.
When I add a new IP, after ~10 seconds I get a green message saying "Changes saved". When I refresh the indicator list, I can find the recently added address. During the add process one core of the CPU works at 100% for several sconds. So at only one address it works, just a bit slow.
When I add 3-4 IPs one-by-one using the web gui (my typing speed is around 3 seconds per IP), I get a red message: "Error adding indicator: Timeout". In this case recently added addresses has not got in the list.

**Comment by jtschichold** [comment]
@pgerencser which type of Miner are you using to add indicators? Please make sure you are using stdlib.localDB Miner

**Comment by pgerencser** [comment]
@jtschichold Thank you for your reply, using stdlib.localDB miner makes it much more faster.
