### ISSUE TITLE
Minemeld Starting sudden issue

### ISSUE THREAD

**Issue by XiQshoner** [PaloAltoNetworks/minemeld#37]
I think this is probably wasted breath as it seems minemeld isn't being supported for free anymore.

However, recently my miners starting acting up. So I was going to restart the minemeld service via CLI. That didn't go to well as I received this error.

Someone@MineMeld:~$ sudo service minemeld start
 * Starting: minemeld                                                                                                                                                                         /opt/minemeld/engine/0.9.52.post1/local/lib/python2.7/site-packages/supervisor/options.py:383: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  return pkg_resources.EntryPoint.parse("x="+spec).load(False)

Might be something with a recent update, I am running Ubuntu LTS 16.0.4 as the build recommends. Any help would be appreciated, as I have these dynamic lists deployed to 80+ firewalls.

**Comment by jtschichold** [comment]
Hi @XiQshoner,
open source MineMeld is still maintained, working on a new release as we speak :-)
The warning you see do not explain the issues with the Miners. Could you add more details about the errors you see on the WebUI?

If you are on 16.04, I suggest upgrading to MineMeld 0.9.60 - it was released some weeks ago.

Thanks,
Luigi

**Comment by XiQshoner** [comment]
Thanks for the quick reply, maybe the Palo Alto live community is just slow.
I ran a apt-get upgrade on my Ubuntu instance and it helped with the starting errors. The miner in question is still polling, if it errors out again I will update this request accordingly.
I will move to 0.9.60 today sometime.

**Comment by XiQshoner** [comment]
The miner in question is recordedfuture.IPRiskList. Essentially, it seems the miner will poll until it errors out. The indicators don't seem to be cycling as usual and old data is not being churned.

On a side note, I ran the sudo /usr/sbin/minemeld-auto-update  and it said that VERSION: 0.9.52 was the best found.

**Comment by jtschichold** [comment]
Could you send me the error you see on the RF Miner?

**Comment by XiQshoner** [comment]
Fortunately, this is now polling with success. If something else happens with this node I will update the ticket.
