### ISSUE TITLE
Documentation: Wrong link location

### ISSUE THREAD

**Issue by jonnynux** [PaloAltoNetworks/minemeld#9]
In this page https://github.com/PaloAltoNetworks/minemeld/wiki/How-To-Write-a-Simple-Miner, the **MineMeld Engine Architecture** link is wrong (actually is https://github.com/PaloAltoNetworks/minemeld-core/docs/architecture.rst). The correct link seems to be https://github.com/PaloAltoNetworks/minemeld-core/blob/master/docs/architecture.rst

**Comment by jtschichold** [comment]
Thanks ! fixed. BTW, if you are looking into building new Miners for MineMeld - check the extension mechanism. Much easier and as powerful as a built-in node.
Example: https://github.com/PaloAltoNetworks/youtube-miner

**Comment by jonnynux** [comment]
Thanks @jtschichold, is what I was searching for. I tried the method in the wiki but this seems better.
